local AbilityDefinitions = {
	["Fireball"] = {
		DisplayName = "Fireball",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 25,
		Range = 115,
		Cooldown = 1.2,
		Color = Color3.fromRGB(255, 95, 42),
		ProjectileSpeed = 115,
		Visual = {
			Shape = "Beam",
			Width = 1.1,
			Lifetime = 0.18,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 190, 70),
		},
		Effects = {},
		Tags = { "Magic", "Fire", "Ranged" },
	},
	["Flame Burst"] = {
		DisplayName = "Flame Burst",
		AbilityType = "Area",
		Targeting = "SelfArea",
		Damage = 16,
		Radius = 22,
		Range = 22,
		Cooldown = 2.4,
		Color = Color3.fromRGB(255, 140, 55),
		Visual = {
			Shape = "AreaRing",
			Height = 0.5,
			Lifetime = 0.35,
			Transparency = 0.35,
			SecondaryColor = Color3.fromRGB(255, 70, 30),
		},
		Effects = {},
		Tags = { "Magic", "Fire", "Area" },
	},
	["Ignite"] = {
		DisplayName = "Ignite",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 34,
		Range = 100,
		Cooldown = 2.1,
		Color = Color3.fromRGB(255, 62, 36),
		ProjectileSpeed = 100,
		Visual = {
			Shape = "Beam",
			Width = 0.85,
			Lifetime = 0.28,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(120, 20, 12),
		},
		Effects = {},
		Tags = { "Magic", "Fire", "Ranged" },
	},
	["Ice Shard"] = {
		DisplayName = "Ice Shard",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 18,
		Range = 120,
		Cooldown = 0.9,
		Color = Color3.fromRGB(135, 225, 255),
		ProjectileSpeed = 145,
		Visual = {
			Shape = "Shard",
			Width = 0.55,
			Lifetime = 0.16,
			Material = Enum.Material.Ice,
			SecondaryColor = Color3.fromRGB(220, 250, 255),
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Ranged" },
	},
	["Frost Bolt"] = {
		DisplayName = "Frost Bolt",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 23,
		Range = 105,
		Cooldown = 1.35,
		Color = Color3.fromRGB(95, 190, 255),
		ProjectileSpeed = 120,
		Visual = {
			Shape = "Beam",
			Width = 0.75,
			Lifetime = 0.22,
			Material = Enum.Material.Ice,
			SecondaryColor = Color3.fromRGB(180, 235, 255),
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Ranged" },
	},
	["Glacier Spike"] = {
		DisplayName = "Glacier Spike",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 30,
		Range = 95,
		Cooldown = 2,
		Color = Color3.fromRGB(195, 245, 255),
		ProjectileSpeed = 95,
		Visual = {
			Shape = "Shard",
			Width = 1.2,
			Lifetime = 0.22,
			Material = Enum.Material.Ice,
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Ranged" },
	},
	["Ice Armor"] = {
		DisplayName = "Ice Armor",
		AbilityType = "Buff",
		Targeting = "SelfBuff",
		Damage = 0,
		Range = 0,
		Cooldown = 8,
		Duration = 5,
		HealthShield = 18,
		Color = Color3.fromRGB(185, 240, 255),
		Visual = {
			Shape = "Aura",
			Size = Vector3.new(8, 8, 8),
			Lifetime = 0.55,
			Transparency = 0.48,
			Material = Enum.Material.ForceField,
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Effects = {
			{ Type = "Shield", Amount = 18, Duration = 5 },
		},
		Tags = { "Magic", "Ice", "Self", "Defensive" },
	},
	["Lightning Bolt"] = {
		DisplayName = "Lightning Bolt",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 35,
		Range = 145,
		Cooldown = 1.8,
		Color = Color3.fromRGB(255, 245, 95),
		ProjectileSpeed = 220,
		Visual = {
			Shape = "Lightning",
			Width = 0.45,
			Lifetime = 0.12,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 255, 255),
		},
		Effects = {},
		Tags = { "Magic", "Lightning", "Ranged" },
	},
	["Spark Shot"] = {
		DisplayName = "Spark Shot",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 15,
		Range = 115,
		Cooldown = 0.55,
		Color = Color3.fromRGB(255, 255, 150),
		ProjectileSpeed = 240,
		Visual = {
			Shape = "Spark",
			Width = 0.35,
			Lifetime = 0.1,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 255, 255),
		},
		Effects = {},
		Tags = { "Magic", "Lightning", "Ranged" },
	},
	["Storm Lance"] = {
		DisplayName = "Storm Lance",
		AbilityType = "Projectile",
		Targeting = "ForwardRay",
		Damage = 27,
		Range = 170,
		Cooldown = 1.35,
		Color = Color3.fromRGB(178, 210, 255),
		ProjectileSpeed = 260,
		Visual = {
			Shape = "Lightning",
			Width = 0.7,
			Lifetime = 0.14,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(235, 245, 255),
		},
		Effects = {},
		Tags = { "Magic", "Lightning", "Ranged" },
	},
	["Blink Surge"] = {
		DisplayName = "Blink Surge",
		AbilityType = "Buff",
		Targeting = "SelfBuff",
		Damage = 0,
		Range = 0,
		Cooldown = 7,
		Duration = 3,
		WalkSpeedMultiplier = 1.45,
		Color = Color3.fromRGB(178, 210, 255),
		Visual = {
			Shape = "Aura",
			Size = Vector3.new(6, 8, 6),
			Lifetime = 0.45,
			Transparency = 0.5,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 255, 180),
		},
		Effects = {
			{ Type = "Speed", Multiplier = 1.45, Duration = 3 },
		},
		Tags = { "Magic", "Lightning", "Self", "Mobility" },
	},
}

-- Future abilities can use other AbilityType/Targeting values such as Melee,
-- Dash, Trap, Drone, Shield, Area, Summon, or SelfBuff.

return AbilityDefinitions
