local AbilityDefinitions = {
	["Fireball"] = {
		DisplayName = "Fireball",
		AbilityType = "Projectile",
		Targeting = "ProjectileExplode",
		Damage = 18,
		Range = 115,
		ExplosionRadius = 14,
		Cooldown = 1.5,
		Color = Color3.fromRGB(255, 95, 42),
		ProjectileSpeed = 90,
		Visual = {
			Shape = "Fireball",
			ProjectileSize = Vector3.new(3, 3, 3),
			ExplosionLifetime = 0.34,
			ExplosionTransparency = 0.38,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 190, 70),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/electronicpingshort.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.55,
			ImpactVolume = 0.45,
			Pitch = 0.9,
		},
		Effects = {},
		Tags = { "Magic", "Fire", "Projectile", "Area" },
	},
	["Flame Burst"] = {
		DisplayName = "Flame Burst",
		AbilityType = "Area",
		Targeting = "SelfArea",
		Damage = 16,
		Radius = 22,
		Range = 22,
		Cooldown = 2.4,
		Color = Color3.fromRGB(255, 140, 55),
		Visual = {
			Shape = "AreaRing",
			Height = 0.5,
			Lifetime = 0.35,
			Transparency = 0.35,
			SecondaryColor = Color3.fromRGB(255, 70, 30),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/bass.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.55,
			ImpactVolume = 0.42,
			Pitch = 0.85,
		},
		Effects = {},
		Tags = { "Magic", "Fire", "Area" },
	},
	["Ignite"] = {
		DisplayName = "Ignite",
		AbilityType = "Raycast",
		Targeting = "Raycast",
		Damage = 34,
		Range = 100,
		Cooldown = 2.1,
		Color = Color3.fromRGB(255, 62, 36),
		Visual = {
			Shape = "Beam",
			Width = 0.85,
			Lifetime = 0.28,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(120, 20, 12),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/electronicpingshort.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.55,
			ImpactVolume = 0.48,
			Pitch = 0.75,
		},
		Effects = {},
		Tags = { "Magic", "Fire", "Raycast" },
	},
	["Ice Shard"] = {
		DisplayName = "Ice Shard",
		AbilityType = "Raycast",
		Targeting = "Raycast",
		Damage = 18,
		Range = 120,
		Cooldown = 0.9,
		Color = Color3.fromRGB(135, 225, 255),
		Visual = {
			Shape = "Shard",
			Width = 0.55,
			Lifetime = 0.16,
			Material = Enum.Material.Ice,
			SecondaryColor = Color3.fromRGB(220, 250, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.45,
			ImpactVolume = 0.42,
			Pitch = 1.25,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Raycast" },
	},
	["Frost Bolt"] = {
		DisplayName = "Frost Bolt",
		AbilityType = "Projectile",
		Targeting = "ProjectileExplode",
		Damage = 16,
		Range = 105,
		ExplosionRadius = 10,
		Cooldown = 1.45,
		Color = Color3.fromRGB(95, 190, 255),
		ProjectileSpeed = 105,
		Visual = {
			Shape = "IceBolt",
			ProjectileSize = Vector3.new(2.2, 2.2, 2.2),
			ExplosionLifetime = 0.28,
			ExplosionTransparency = 0.45,
			Material = Enum.Material.Ice,
			SecondaryColor = Color3.fromRGB(180, 235, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.48,
			ImpactVolume = 0.44,
			Pitch = 1.05,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Projectile", "Area" },
	},
	["Ice Nova"] = {
		DisplayName = "Ice Nova",
		AbilityType = "Area",
		Targeting = "DelayedSelfArea",
		Damage = 22,
		Radius = 30,
		Cooldown = 4.5,
		SpreadDuration = 1.35,
		SpreadSteps = 7,
		Color = Color3.fromRGB(150, 230, 255),
		Visual = {
			Shape = "SpreadingSpikes",
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.52,
			ImpactVolume = 0.46,
			Pitch = 0.85,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Area", "Self" },
	},
	["Glacier Spike"] = {
		DisplayName = "Glacier Spike",
		AbilityType = "Raycast",
		Targeting = "Raycast",
		Damage = 30,
		Range = 95,
		Cooldown = 2,
		Color = Color3.fromRGB(195, 245, 255),
		Visual = {
			Shape = "Shard",
			Width = 1.2,
			Lifetime = 0.22,
			Material = Enum.Material.Ice,
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.52,
			ImpactVolume = 0.5,
			Pitch = 0.75,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Raycast" },
	},
	["Glacier Path"] = {
		DisplayName = "Glacier Path",
		AbilityType = "Wave",
		Targeting = "LineWave",
		Damage = 24,
		Range = 82,
		Width = 8,
		Cooldown = 4,
		TravelDuration = 1.9,
		WaveSteps = 11,
		Color = Color3.fromRGB(195, 245, 255),
		Visual = {
			Shape = "GrowingIceLine",
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.55,
			ImpactVolume = 0.5,
			Pitch = 0.75,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Wave", "Ground" },
	},
	["Hail Crash"] = {
		DisplayName = "Hail Crash",
		AbilityType = "TargetedArea",
		Targeting = "TargetedArea",
		Damage = 28,
		Range = 100,
		Radius = 16,
		Delay = 0.65,
		Cooldown = 5,
		Color = Color3.fromRGB(210, 250, 255),
		Visual = {
			Shape = "TargetedBurst",
			Height = 0.3,
			Lifetime = 0.4,
			Transparency = 0.42,
			SecondaryColor = Color3.fromRGB(240, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.5,
			ImpactVolume = 0.5,
			Pitch = 0.95,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Area", "Targeted" },
	},
	["Ice Armor"] = {
		DisplayName = "Ice Armor",
		AbilityType = "Buff",
		Targeting = "SelfBuff",
		Damage = 0,
		Range = 0,
		Cooldown = 8,
		Duration = 5,
		HealthShield = 18,
		Color = Color3.fromRGB(185, 240, 255),
		Visual = {
			Shape = "Aura",
			Size = Vector3.new(8, 8, 8),
			Lifetime = 0.55,
			Transparency = 0.48,
			Material = Enum.Material.ForceField,
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/button.wav",
			CastVolume = 0.45,
			Pitch = 1.1,
		},
		Effects = {
			{ Type = "Shield", Amount = 18, Duration = 5 },
		},
		Tags = { "Magic", "Ice", "Self", "Defensive" },
	},
	["Ice Warden"] = {
		DisplayName = "Ice Warden",
		AbilityType = "Summon",
		Targeting = "Summon",
		Damage = 0,
		Range = 65,
		Cooldown = 12,
		Duration = 18,
		Color = Color3.fromRGB(160, 230, 255),
		SummonName = "Ice Warden",
		SummonHealth = 130,
		SummonDamage = 9,
		SummonScale = 0.85,
		SummonWalkSpeed = 13,
		SummonDetectRadius = 70,
		SummonAttackRadius = 8,
		SummonAttackCooldown = 1.25,
		Visual = {
			Shape = "SummonCircle",
			SummonRadius = 7,
			SecondaryColor = Color3.fromRGB(235, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/snap.wav",
			CastVolume = 0.55,
			Pitch = 0.7,
		},
		Effects = {},
		Tags = { "Magic", "Ice", "Summon", "Ally" },
	},
	["Lightning Bolt"] = {
		DisplayName = "Lightning Bolt",
		AbilityType = "Raycast",
		Targeting = "Raycast",
		Damage = 35,
		Range = 145,
		Cooldown = 1.8,
		Color = Color3.fromRGB(255, 245, 95),
		Visual = {
			Shape = "Lightning",
			Width = 0.45,
			Lifetime = 0.12,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/electronicpingshort.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.5,
			ImpactVolume = 0.5,
			Pitch = 1.35,
		},
		Effects = {},
		Tags = { "Magic", "Lightning", "Raycast" },
	},
	["Spark Shot"] = {
		DisplayName = "Spark Shot",
		AbilityType = "Raycast",
		Targeting = "Raycast",
		Damage = 15,
		Range = 115,
		Cooldown = 0.55,
		Color = Color3.fromRGB(255, 255, 150),
		Visual = {
			Shape = "Spark",
			Width = 0.35,
			Lifetime = 0.1,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 255, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/electronicpingshort.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.38,
			ImpactVolume = 0.35,
			Pitch = 1.6,
		},
		Effects = {},
		Tags = { "Magic", "Lightning", "Raycast" },
	},
	["Storm Lance"] = {
		DisplayName = "Storm Lance",
		AbilityType = "Raycast",
		Targeting = "Raycast",
		Damage = 27,
		Range = 170,
		Cooldown = 1.35,
		Color = Color3.fromRGB(178, 210, 255),
		Visual = {
			Shape = "Lightning",
			Width = 0.7,
			Lifetime = 0.14,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(235, 245, 255),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/electronicpingshort.wav",
			ImpactSoundId = "rbxasset://sounds/collide.wav",
			CastVolume = 0.52,
			ImpactVolume = 0.48,
			Pitch = 1.15,
		},
		Effects = {},
		Tags = { "Magic", "Lightning", "Raycast" },
	},
	["Blink Surge"] = {
		DisplayName = "Blink Surge",
		AbilityType = "Buff",
		Targeting = "SelfBuff",
		Damage = 0,
		Range = 0,
		Cooldown = 7,
		Duration = 3,
		WalkSpeedMultiplier = 1.45,
		Color = Color3.fromRGB(178, 210, 255),
		Visual = {
			Shape = "Aura",
			Size = Vector3.new(6, 8, 6),
			Lifetime = 0.45,
			Transparency = 0.5,
			Material = Enum.Material.Neon,
			SecondaryColor = Color3.fromRGB(255, 255, 180),
		},
		Audio = {
			CastSoundId = "rbxasset://sounds/electronicpingshort.wav",
			CastVolume = 0.48,
			Pitch = 1.45,
		},
		Effects = {
			{ Type = "Speed", Multiplier = 1.45, Duration = 3 },
		},
		Tags = { "Magic", "Lightning", "Self", "Mobility" },
	},
}

-- Current reusable targeting/behavior types:
-- Raycast, ProjectileExplode, SelfArea, DelayedSelfArea, LineWave,
-- TargetedArea, Summon, and SelfBuff. Future types can add Dash, Trap,
-- Deployable, Channel, Chain, Cone, or Aura without changing class data shape.

return AbilityDefinitions
