local ClassDefinitions = {
	["Fire Caster"] = {
		DisplayName = "Fire Caster",
		Archetype = "Mage",
		Element = "Fire",
		Role = "Burst damage",
		RoleTags = { "Easy", "Ranged", "Area" },
		Icon = "F",
		SortOrder = 10,
		Description = "Aggressive caster with simple, high-pressure fire abilities.",
		Selectable = true,
		StarterAbilities = { "Fireball", "Flame Burst", "Ignite" },
	},
	["Lightning Mage"] = {
		DisplayName = "Lightning Mage",
		Archetype = "Mage",
		Element = "Lightning",
		Role = "Speed and precision",
		RoleTags = { "Mobile", "Ranged", "Fast" },
		Icon = "L",
		SortOrder = 30,
		Description = "Fast striker with long range and quick follow-up abilities.",
		Selectable = true,
		StarterAbilities = { "Lightning Bolt", "Spark Shot", "Blink Surge" },
	},
	["Ice Mage"] = {
		DisplayName = "Ice Mage",
		Archetype = "Mage",
		Element = "Ice",
		Role = "Control and survival",
		RoleTags = { "Easy", "Control", "Defensive" },
		Icon = "I",
		SortOrder = 20,
		Description = "Defensive mage with spreading ice, projectile bursts, and ground control.",
		Selectable = true,
		StarterAbilities = { "Ice Shard", "Frost Bolt", "Ice Nova", "Glacier Spike", "Glacier Path", "Hail Crash", "Ice Armor", "Ice Warden" },
	},
	["Scrap Knight"] = {
		DisplayName = "Scrap Knight",
		Archetype = "Fighter",
		Element = "Scrap",
		Role = "Tanky brawler",
		RoleTags = { "Easy", "Tanky", "Melee" },
		Icon = "K",
		SortOrder = 40,
		Description = "Durable junk-armored fighter with close-range shockwaves and shields.",
		Selectable = true,
		StarterAbilities = { "Scrap Slam", "Rusty Shield", "Junk Toss", "Magnet Pull", "Armor Up", "Scrap Quake", "Guard Breaker", "Trash Charge" },
	},
	["Tech Warrior"] = {
		DisplayName = "Tech Warrior",
		Archetype = "Fighter",
		Element = "Tech",
		Role = "Gadgets and shots",
		RoleTags = { "Ranged", "Utility", "Tech" },
		Icon = "T",
		SortOrder = 50,
		Description = "Gadget fighter with blasters, drones, and targeted tech bursts.",
		Selectable = true,
		StarterAbilities = { "Pulse Shot", "Rocket Pop", "Static Mine", "Drone Buddy", "Overclock", "Laser Sweep", "Gadget Burst", "Repair Patch" },
	},
	["Toxic Scavenger"] = {
		DisplayName = "Toxic Scavenger",
		Archetype = "Fighter",
		Element = "Toxic",
		Role = "Area denial",
		RoleTags = { "Area", "Control", "Ranged" },
		Icon = "X",
		SortOrder = 60,
		Description = "Messy area fighter with toxic puddles, clouds, and scavenged tricks.",
		Selectable = true,
		StarterAbilities = { "Sludge Lob", "Toxic Cloud", "Acid Splash", "Gas Mask", "Waste Wave", "Poison Needle", "Muck Trap", "Scavenger Rush" },
	},
	["Junk Engineer"] = {
		DisplayName = "Junk Engineer",
		Archetype = "Builder",
		Element = "Junk",
		Role = "Summons and tools",
		RoleTags = { "Builder", "Summon", "Support" },
		Icon = "E",
		SortOrder = 70,
		Description = "Builder class with deployable helpers and chunky utility abilities.",
		Selectable = true,
		StarterAbilities = { "Mini Turret", "Wrench Toss", "Scrap Wall", "Fixer Bot", "Bolt Burst", "Trap Box", "Power Field", "Overbuild" },
	},
	["Shadow Duelist"] = {
		DisplayName = "Shadow Duelist",
		Archetype = "Fighter",
		Element = "Shadow",
		Role = "Fast duelist",
		RoleTags = { "Mobile", "Ranged", "Skill" },
		Icon = "S",
		SortOrder = 80,
		Description = "Dark striker with quick shots, clones, and narrow but strong attacks.",
		Selectable = true,
		StarterAbilities = { "Shadow Bolt", "Dark Step", "Night Slash", "Shade Clone", "Gloom Burst", "Void Needle", "Duel Mark", "Blackout" },
	},
	["Stone Guardian"] = {
		DisplayName = "Stone Guardian",
		Archetype = "Fighter",
		Element = "Earth",
		Role = "Defense and control",
		RoleTags = { "Easy", "Tanky", "Control" },
		Icon = "G",
		SortOrder = 90,
		Description = "Heavy guardian with rock waves, shields, and forgiving area attacks.",
		Selectable = true,
		StarterAbilities = { "Rock Toss", "Stone Wall", "Ground Pound", "Pebble Spray", "Guardian Shell", "Fault Line", "Boulder Drop", "Earth Anchor" },
	},
	["Wind Runner"] = {
		DisplayName = "Wind Runner",
		Archetype = "Fighter",
		Element = "Air",
		Role = "Mobility and wide shots",
		RoleTags = { "Mobile", "Easy", "Ranged" },
		Icon = "W",
		SortOrder = 100,
		Description = "Fast air fighter with wide gusts and movement-friendly attacks.",
		Selectable = true,
		StarterAbilities = { "Gust Shot", "Air Dash", "Cyclone Spin", "Wind Wall", "Feather Burst", "Sky Lance", "Tailwind", "Storm Ring" },
	},
}

for _, classDefinition in pairs(ClassDefinitions) do
	classDefinition.StarterSpells = classDefinition.StarterAbilities
end

return ClassDefinitions
