local ServerScriptService = game:GetService("ServerScriptService")

local MapService = require(ServerScriptService.MapService)
local SafeZoneService = require(ServerScriptService.SafeZoneService)
local CombatService = require(ServerScriptService.CombatService)
local AnalyticsService = require(ServerScriptService.AnalyticsService)
local SpellService = require(ServerScriptService.SpellService)
local ClassService = require(ServerScriptService.ClassService)
local PlayerLifecycleService = require(ServerScriptService.PlayerLifecycleService)
local ProgressionService = require(ServerScriptService.ProgressionService)
local MobService = require(ServerScriptService.MobService)
local BossService = require(ServerScriptService.BossService)

MapService:Init()
SafeZoneService:Init()
AnalyticsService:Init()
CombatService:Init()
SpellService:Init()
ClassService:Init()
PlayerLifecycleService:Init()
ProgressionService:Init()
MobService:Init()
BossService:Init()
